apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi
  labels:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/version: 0.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taxi
      app.kubernetes.io/version: 0.0.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: taxi
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
      - name: taxi-2
        image: upshift.mirror-registry.qe.devcluster.openshift.com:5000/cbanavik/taxi:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: web-files
          mountPath: /usr/share/booktaxi
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      initContainers:
      - name: my-init-container-1
        image: busybox
        command: ['sh', '-c', 'echo my-init-container-1 start; sleep 2;echo my-init-container-1 complete;']
      - name: my-init-container-2
        image: busybox
        command: ['sh', '-c', 'echo my-init-container-2 start; sleep 2;echo my-init-container-2 complete;']

      volumes:
      - name: web-files
        configMap:
          name: www-files
